spring:
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
springdoc:
  show-actuator: true
  api-docs:
    path: /api
server:
  port: 8081